compact: true
framework:
  - terraform
  - dockerfile
download-external-modules: false
external-checks-dir:
  - .checkov/policies
quiet: true
soft-fail: false
skip-path:
  - '\.terraform'
  - '\.venv'
  - '\.checkov/fixtures'
